local: &local
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  socket: <%= ['/opt/local/var/run/mysql5/mysqld.sock', # darwinports
               '/opt/local/var/run/mysqld/mysqld.sock', # darwinports, again
               '/var/run/mysqld/mysqld.sock',           # ubuntu/debian
               '/tmp/mysql.sock'].select { |f| File.exist? f }.first %>


development:
  <<: *local
  database: sbonrails_development

test: &TEST
  <<: *local
  database: sbonrails_test

production:
  <<: *local
  database: sbonrails_production

cucumber:
  <<: *TEST

